### ISSUE TITLE
Automatically disable on subscribed channels

### ISSUE THREAD

**Issue by cabbagefork** [AlyoshaVasilieva/luminous-ttv-ext#2]
Not really an issue, but more of a suggestion. I'd like to see an option for the extension to automatically detect and disable itself on channels I'm already subscribed too. 

It would be a nice QoL addition that removes the red error message whenever I'm watching a subbed streamer and the server isn't running. It'd also remove the extra delay that is being added when proxying.

**Comment by AlyoshaVasilieva** [comment]
Unfortunately I'm probably not competent enough at extension dev to do this. [ttv-lol-pro](https://github.com/younesaassila/ttv-lol-pro) can, apparently, and as of v1.5.0 you can specify servers for it to use. luminous-ttv v0.5.0+ works with that.

**Comment by cabbagefork** [comment]
Thank you; I left TTV since it no longer worked for me. I'll just keep using your server while on TTV PRO's extension instead.
