### ISSUE TITLE
This stops working 1day ago (at least prevents me from watching stream without bufffering)

### ISSUE THREAD

**Issue by MrManinBlack1337** [AlyoshaVasilieva/luminous-ttv-ext#6]
Not sure if it is related to MV3 like the other topic mentioned, but it does not stop the playback completely instead it just freezes the video every 2 seconds and repeat. Playback went smooth after I disable the extension and restart browser.

Hopefully this can be fixed because I love the extension. Thanks

**Comment by AlyoshaVasilieva** [comment]
Depending on what country you're routing requests through, you might get unlucky and have very bad connection to the Twitch server serving you video chunks, where your download speed is less than the video's bitrate. For me, usually reloading the stream or switching countries fixes it.

If when this is happening, you reduce the quality to like 480p, does it keep happening?

**Comment by MrManinBlack1337** [comment]
Scratch that, it magically fixed itself. I disabled the extension for 1 day and now the next day it is working fine again wtf?
